spring:
  ai:
    ollama:
      chat:
        model: gemma3:4b-it-q4_K_M
      base-url: http://localhost:11434
  main:
    allow-circular-references: true
  application:
    name: ChatAIService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chat_ai}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public


server:
  port: 8080